---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key

  - repo: git://github.com/luminopia/pre-commit-hooks
    rev: v0.0.6
    hooks:
      - id: enforce-action-comments

  # YAML is complicated (eg. auto converting `NO` to `false`).
  # This lint tool forbids such features.
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint

  - repo: git://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: local
    hooks:
      # https://github.com/hadolint/hadolint
      - id: dockerfile-lint
        name: Dockerfile Lint
        language: docker_image
        entry: hadolint/hadolint:v1.7.0 hadolint
        files: ^.*Dockerfile.*$

      # https://github.com/koalaman/shellcheck
      - id: shellcheck-lint
        name: Shellcheck
        language: docker_image
        entry: koalaman/shellcheck:v0.5.0
        types: [shell]

      # https://github.com/igorshubovych/markdownlint-cli
      - id: markdown-lint
        name: Markdown Lint
        language: node
        additional_dependencies: [markdownlint-cli]
        entry: markdownlint
        types: [markdown]
        args: [--config, .markdownlintrc]
