[package]
name = "mlcb-rust-csv"
version = "0.1.0"
authors = ["Alex Wendland <me@alexwendland.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"csv" = "1"
"chrono" = "0.4"